### PR TITLE
Ported to Python3

### PR DESCRIPTION
**Pull request by Sparrrgh**
I ported the whole tool in Python3, you should make a branch with the old version for people still using Python2, but I think the new version should go in master because Py2 EOL is in 2 months

### CODE REVIEW

**Comment by ticarpi** [comment]
Guys, thank you so much for taking the time to work on this.  
I'm sorry I couldn't merge the PR, but as you'll see I was working on this already (commit 0e0b33566972f6b2186ad9c682239de1fd50a672) and it was held up as I was also making some other tweaks and improvements - as well as groundwork for some new additions that will be coming soon.

**Comment by jacopotediosi** [comment]
Don't worry
I hope that this people will make their own repository with their own version of the tool
It would be a pity to reduce everything to a PR, after they had to rewrite all this really bad code from scratch

**Comment by jacopotediosi** [comment]
Moreover, I think you should give them some credits, because it's obvious you're stealing their code

**Comment by Sparrrgh** [comment]
So you randomly happened to be porting to Python3 while I did?
What a strange coincidence!
You're free to not credit us, but it's pretty obvious what you're doing here.

**Pull request closed without merging**
